### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by FilipReinholdson** [axisgroup/RxQ#17]
Hi, Thanks for some great work! It is however not working for me...

Playing with the "chart-with-filter" tutorial example. Running with Node: http-server -a localhost -p 3000.

Console:
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined at Object.subscribeToResult (rxq.js:4340) at MergeMapSubscriber._innerSub (rxq.js:10159) at MergeMapSubscriber._tryNext (rxq.js:10156) at MergeMapSubscriber._next (rxq.js:10139) at MergeMapSubscriber.Subscriber.next (rxq.js:2756) at RefCountSubscriber.Subscriber._next (rxq.js:2792) at RefCountSubscriber.Subscriber.next (rxq.js:2756) at ReplaySubject.Subject.next (rxq.js:2379) at ReplaySubject.next (rxq.js:8807) at ConnectableSubscriber.Subscriber._next (rxq.js:2792)

What can be the problem, any hints?

![image](https://cloud.githubusercontent.com/assets/16564277/23092176/77aec5ca-f5c5-11e6-9f6c-97552249f89f.png)

**Comment by skokenes** [comment]
Hi Filip, thanks for finding this bug. I have a fix in place and will upload at some point this weekend - traveling at the moment

**Comment by rvaheldendaten** [comment]
Hi! Same issue here!
Is it related to Qlik Sense 3.2SR1, or is it a more general thing?

Thx,
Roland

**Comment by skokenes** [comment]
Nah it's me not copying and pasting some new code properly

**Comment by rvaheldendaten** [comment]
I tested your two previous releases, and I run into the same problem :-(

https://github.com/axisgroup/RxQ/releases/tag/v0.5.1
https://github.com/axisgroup/RxQ/releases/tag/v0.5.0

**Comment by skokenes** [comment]
Hi friends,

I have fixed the issue and published version 0.5.3. I apologize for the delay
https://github.com/axisgroup/RxQ/releases/tag/v0.5.3

Please let me know if you have any more issues
