### ISSUE TITLE
Delta Mode

### ISSUE THREAD

**Issue by instanceofnull** [axisgroup/RxQ#29]
Provide a way to enable delta mode where applicable.

**Comment by skokenes** [comment]
enigma.js opts into this by default, with a global setting to opt out. You can also write request interceptors to do selective opt ins/outs

RxQ can do something similar. I am leaning towards default opt out of delta mode, with options to opt in across the board as well as define overrides for qType & method combinations. I'm thinking an API within the config like:

```javascript
const config = {
  // ...usual config stuff,
  delta: true / false,
  deltaOverrides: [
    {
      qType: "GenericObject",
      includeDelta: ["GetProperties", "GetLayout"]
      // alternatively, excludeDelta
    }
  ]
}
```

First step is to add in the ability to even handle delta mode though. It seems most (all?) calls use it -> need to investigate further

**Comment by skokenes** [comment]
done in https://github.com/axisgroup/RxQ/tree/v1.1.0

the API is slightly different from above, will have to update docs
