### ISSUE TITLE
Add WebSocket notification stream on Global handle

### ISSUE THREAD

**Issue by skokenes** [axisgroup/RxQ#46]
A Global Handle is 1 to 1 with a session / WebSocket. It is useful for debugging (and other usecases) to be able to monitor events related to the entire session and the underlying WebSocket. 

Discussion in Slack led to the idea of the Global Handle having a property on it called `notification$` that is a stream of session events. These events could cover:

- the websocket closing
- the websocket being opened and ready
- websocket authentication failures? (this can already be caught in Global handle error I believe)
- any error received from the engine api
- traffic sent to the engine
- traffic received from the engine
- suspense status?

Example Usage:
```javascript
const notifications$ = session$.pipe(
    switchMap(h => h.notification$)
)
```

This would stream notifications in the format `{ type, data }`

So you could retrieve close events like
```javascript
const sessionClosed$ = session$.pipe(
    switchMap(h => h.notification$),
    filter(n => n.type === "socket:close")
)
```

**Comment by instanceofnull** [comment]
https://codesandbox.io/s/qqp8m3jy46

**Comment by skokenes** [comment]
done in v1.1.0 branch https://github.com/axisgroup/RxQ/tree/v1.1.0. tracking merge to master in @ #47
