### ISSUE TITLE
Connection Issues when connecting to engine and not directly to app

### ISSUE THREAD

**Issue by sunpar** [axisgroup/RxQ#61]
Connecting to sense engine was fine as of 2.0.0, and broken after that. Websocket returns a 301 error because, i think, of a missing '/' after 'app'.

See codebox here: https://codesandbox.io/s/n4zv7l32oj

Issue seems directly related to a commit I made (sorry!): https://github.com/axisgroup/RxQ/commit/df5bcb50a890404eab53195a2140f138ea6ea302

I'm trying to remember why deleted the '/' after app when an app ID is not given -- I think because I didn't want the double '/' when identity is given, since previously it was giving double slashes ('//'). However, I think the '/' should be deleted before identity and added after app.

**Comment by skokenes** [comment]
Closed with v2.0.3
