### ISSUE TITLE
qAsk and qAskReplay need an option to retry on error

### ISSUE THREAD

**Issue by sunpar** [axisgroup/RxQ#63]
I frequently need to retry things like GetLayout when I get an error from Qlik, and I also like to use qAsk to get my layouts, but I can't do both at the same time.

I made a mess out of trying to create a new branch for this when I pushed my expanded util options by pushing to master by the way. So you should probably somehow restrict my ability to push to master.

**Comment by skokenes** [comment]
Ok I will revert master back to what it was before your commits tonight and
remove the ability for you to push to master, since no one should be doing
that :)

Re: retry, why can't you use that with qAsk? Can you reproduce the
situation where this doesn't work?

If a GetLayout call errors in a qAsk call, retry after the qAsk should
capture that error

**Comment by sunpar** [comment]
Retry needs to go inside the switch map, or it won’t work quite the way we want it to. The documentation on catch/catchError is useful for this: https://www.learnrxjs.io/operators/error_handling/catch.html

I won’t be near my computer for some time, but will post working/non-working examples when I’m back.

**Comment by skokenes** [comment]
It sounds like your usecase is that you only want to retry based on the API method call failing, not on some call earlier in the Observable chain. In that case, you should implement your own operator in user land using switchMap. Something like:

```javascript
import { retry, switchMap } from "rxjs/operators";
import { invalidations } from "rxq";

function getLayoutWithRetry(source) {
  return function(retryTimes) {
    return source.pipe(
      switchMap(h => h.ask("GetLayout").pipe(retry(retryTimes)))
    )
  }
}

const layouts = handle.pipe(
  invalidations(true),
  getLayoutWithRetry(3)
);
```
